import { Router } from 'express';
import path from 'path';
import fs from 'fs';
import ffmpegPath from 'ffmpeg-static';
import { TEMP_DIR } from '../../config';
import { ensureBinary } from '../../binaryManager';
import { executeYtDlpWithRetry } from '../../ytDlpRunner';
import { fetchDirectSubtitleTrack } from '../../subtitleHelper';
import { DecodedCaptionToken } from '../../types';
import { metadataCache, captionCache, extractVideoId } from '../../cacheManager';

export const mediaSubtitleRouter = Router();

// Endpoint: Download native YouTube subtitle track directly without AI translation
mediaSubtitleRouter.get('/caption', async (req, res) => {
  const rawToken = (req.query.token || req.query.trackId) as string;
  const url = req.query.url as string;

  if (!url || !rawToken) return res.status(400).send("Missing required parameters");

  const videoId = extractVideoId(url);

  if (rawToken.startsWith('http')) {
    try {
      const content = await fetchDirectSubtitleTrack(rawToken);
      return res.send(content);
    } catch (e) {
      return res.status(500).send("Failed to download legacy caption URL.");
    }
  }

  let isAuto = false;
  let lang = '';
  let directUrl: string | undefined;

  try {
    const jsonStr = Buffer.from(rawToken, 'base64').toString('utf-8');
    const decoded: DecodedCaptionToken = JSON.parse(jsonStr);
    isAuto = decoded.isAuto;
    lang = decoded.lang;
    directUrl = decoded.directUrl;
  } catch (e) {
    return res.status(400).send("Invalid Caption Token");
  }

  const captionKey = `${videoId}_${lang}_${isAuto ? 'auto' : 'manual'}`;
  const cachedCaption = captionCache.get(captionKey);
  if (cachedCaption) {
    console.log(`[Caption] Serving subtitle for '${captionKey}' from captionCache.`);
    return res.send(cachedCaption);
  }

  if (!directUrl) {
    const cachedData = metadataCache.get(videoId);
    if (cachedData && cachedData.info) {
      const tracksObj = isAuto ? cachedData.info.automatic_captions : cachedData.info.subtitles;
      if (tracksObj && tracksObj[lang]) {
        const formats = tracksObj[lang];
        const preferredFormat = Array.isArray(formats) 
          ? (formats.find((f: any) => f.ext === 'vtt' || f.ext === 'json3' || f.ext === 'srv3') || formats[0]) 
          : undefined;
        if (preferredFormat && preferredFormat.url) {
          directUrl = preferredFormat.url;
          console.log(`[Caption] Recovered signed direct track URL from metadataCache for '${lang}'.`);
        }
      }
    }
  }

  if (directUrl) {
    try {
      console.log(`[Caption] Fetching YouTube direct native subtitle track for '${lang}'...`);
      let content = await fetchDirectSubtitleTrack(directUrl);
      if (content && content.length > 10) {
        captionCache.set(captionKey, content);
        return res.send(content);
      }
    } catch (directErr: any) {
      console.warn(`[Caption] Direct HTTP subtitle fetch failed (${directErr?.message}). Proceeding with yt-dlp...`);
    }
  }

  await ensureBinary();

  const tempId = `sub_${Date.now()}_${Math.random().toString(36).substring(7)}`;
  const outputTemplate = path.join(TEMP_DIR, `${tempId}.%(ext)s`);

  try {
    console.log(`[Caption] Fetching YouTube native subtitle track via yt-dlp for video '${videoId}' (lang: ${lang})...`);
    const args = [
      url,
      '--skip-download',
      '--convert-subs', 'srt',
      '--output', outputTemplate,
      '--ffmpeg-location', ffmpegPath as string,
    ];

    if (isAuto) args.push('--write-auto-sub', '--sub-lang', lang);
    else args.push('--write-sub', '--sub-lang', lang);

    await executeYtDlpWithRetry(args);

    const files = fs.readdirSync(TEMP_DIR);
    const generatedFile = files.find(f => f.startsWith(tempId) && (f.endsWith('.srt') || f.endsWith('.vtt')));

    if (!generatedFile) {
      throw new Error(`Subtitle file for '${lang}' not generated by yt-dlp.`);
    }

    const filePath = path.join(TEMP_DIR, generatedFile);
    const content = fs.readFileSync(filePath, 'utf-8');

    files.filter(f => f.startsWith(tempId)).forEach(f => {
      try { fs.unlinkSync(path.join(TEMP_DIR, f)); } catch (e) {}
    });

    captionCache.set(captionKey, content);
    return res.send(content);

  } catch (error: any) {
    try {
      const files = fs.readdirSync(TEMP_DIR);
      files.filter(f => f.startsWith(tempId)).forEach(f => { try { fs.unlinkSync(path.join(TEMP_DIR, f)); } catch(e) {} });
    } catch (e) {}

    console.error("YT-DLP Caption Error:", error?.message);
    return res.status(500).send("Subtitle download failed.");
  }
});
